use_frameworks!

target 'CocoapodsExample_Example' do
  pod 'CocoapodsExample', :path => '../'

  target 'CocoapodsExample_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
